global:
  scrape_interval: 15s
scrape_configs:
  # scrape OpenTelemetry Collector metrics (includes k6 remote‑write data that the collector reshapes, now sent to port 9465)
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
