spring:
  datasource:
    url: jdbc:postgresql://postgres_order:5432/orderdb
    username: order
    password: order
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: inventory-group
